"""Ask AgentCFO – Financial advisory chatbot endpoint"""

import json
import logging
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import List, Optional
from app.database import get_db
from app import models
from app.dependencies import get_current_user
from app.services.nova_client import NovaClient
from app.services.embeddings import VectorStore

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api", tags=["ask-cfo"])


class ChatMessage(BaseModel):
    role: str        # "user" | "assistant"
    content: str


class AskCFORequest(BaseModel):
    question: str
    analysis_id: Optional[str] = None
    chat_history: List[ChatMessage] = []
    voice_response: bool = False
    voice_id: str = "Matthew"
    selected_text: Optional[str] = None
    selected_section: Optional[str] = None


class AskCFOResponse(BaseModel):
    answer: str
    audio_base64: Optional[str] = None
    audio_mime_type: Optional[str] = None


# =====================================================================
# AgentCFO System Prompt (CFO-level financial advisor)
# =====================================================================

AGENTCFO_SYSTEM_PROMPT = """You are AgentCFO, an AI-powered Chief Financial Officer assistant designed to advise company leadership based on financial reports generated by CFONE.

Your role:
You provide strategic CFO-level guidance to CEOs, founders, and executives asking follow-up questions after a financial analysis report.

Core principles:
1. Act like a real CFO advisor – provide practical financial advice a CFO would give to a CEO
2. Reference financial metrics from the report when explaining decisions
3. Prioritize financial health (liquidity, profitability, debt management, cost optimization, revenue growth)
4. Give structured, actionable responses
5. Detect and highlight financial risks automatically
6. Provide concise, executive-level guidance (avoid academic explanations)
7. Focus on strategic decision-making, not generic chatbot responses

Response structure:
When answering questions, structure your response as follows:

**Financial Insight**
Brief explanation of the current situation based on financial metrics.

**Recommendation**
Clear, actionable advice the CEO should take immediately.

**Expected Impact**
Quantified or qualitative explanation of what improvement this action could create.

**Risk Mitigation** (if applicable)
Additional steps to manage identified risks.

Tone:
- Professional, concise, strategic
- Advisory (like addressing a CEO in a board meeting)
- Data-driven and fact-based
- Focused on practical outcomes

Risk detection:
If the question relates to financial risks (low runway, high debt, low margin, etc.), always highlight the risk level and severity.

When answering:
1. Always reference specific financial numbers from the report context
2. Provide realistic, implementable recommendations
3. Explain both upside and downside scenarios when relevant
4. Flag any critical decisions or trade-offs

If the question is unrelated to finance:
Politely state that your expertise is limited to financial strategy and business operations.

If insufficient data is available:
Explain what additional financial data would be required to answer properly.

Remember: You are NOT a generic chatbot. You are a trusted CFO advisor speaking to company leadership."""


# =====================================================================
# Helper: Build AgentCFO prompt with financial context
# =====================================================================

def _build_agentcfo_context_prompt(
    question: str,
    financial_report: dict,
    chat_history: List[ChatMessage],
    selected_text: Optional[str] = None,
    selected_section: Optional[str] = None,
    retrieved_chunks: Optional[List[dict]] = None,
) -> str:
    """
    Build the full prompt with financial report context injected.
    
    This ensures the AI reasons from the actual financial data, not estimates.
    """
    # Extract key metrics
    fin_health = financial_report.get("section_1_financial_health", {})
    cashflow = financial_report.get("section_2_cash_flow_forecast", {})
    risk = financial_report.get("section_3_risk_alerts", {})
    actions = financial_report.get("section_6_recommended_actions", {})

    # Build financial context block
    context_lines = [
        "FINANCIAL REPORT CONTEXT:",
        "=" * 70,
        "",
    ]
    
    if isinstance(fin_health, dict):
        context_lines.extend([
            "Financial Health:",
            f"  • Total Revenue: ${fin_health.get('revenue', {}).get('total', 0):,.2f}",
            f"  • Total Expenses: ${fin_health.get('expenses', {}).get('total', 0):,.2f}",
            f"  • Net Profit Margin: {fin_health.get('metrics', {}).get('net_profit_margin', 0):.2f}%",
            "",
        ])
    
    if isinstance(cashflow, dict):
        context_lines.extend([
            "Cash Flow:",
            f"  • Monthly Burn Rate: ${cashflow.get('monthly_burn_rate', 0):,.2f}",
            f"  • Cash Runway: {cashflow.get('runway_months', 0):.2f} months",
            "",
        ])
    
    if isinstance(risk, dict):
        context_lines.extend([
            "Risk Assessment:",
            f"  • Risk Score: {risk.get('risk_score', 'N/A')}/100",
            f"  • Risk Level: {risk.get('risk_level', 'Unknown').upper()}",
            "",
        ])

    if isinstance(actions, dict):
        executive_summary = actions.get("executive_summary")
        recommended_actions = actions.get("recommended_actions", [])
        if executive_summary:
            context_lines.extend([
                "Executive Summary:",
                executive_summary,
                "",
            ])
        if recommended_actions:
            context_lines.append("Top Recommended Actions:")
            for action in recommended_actions[:3]:
                if isinstance(action, dict):
                    context_lines.append(
                        f"  • {action.get('action', 'Action')}: {action.get('details', '')}"
                    )
            context_lines.append("")

    if selected_text:
        context_lines.extend([
            "USER SELECTED REPORT TEXT:",
            "=" * 70,
            f"Section: {selected_section or 'Report'}",
            selected_text,
            "",
        ])

    if retrieved_chunks:
        context_lines.extend([
            "SUPPORTING EVIDENCE FROM SOURCE DOCUMENTS:",
            "=" * 70,
            "",
        ])
        for idx, chunk in enumerate(retrieved_chunks[:4], start=1):
            metadata = chunk.get("metadata", {})
            filename = metadata.get("filename", "source document")
            similarity = chunk.get("similarity_score", 0)
            context_lines.extend([
                f"Evidence {idx} ({filename}, relevance {similarity:.2f}):",
                chunk.get("chunk_text", ""),
                "",
            ])
    
    # Add conversation history
    history_lines = []
    if chat_history:
        history_lines = ["Previous Conversation:", "=" * 70, ""]
        for msg in chat_history[-6:]:  # Keep last 6 turns to avoid token overflow
            role = "CEO" if msg.role == "user" else "AgentCFO"
            history_lines.append(f"{role}: {msg.content}")
        history_lines.append("")
    
    # Build final prompt
    full_prompt = "\n".join(context_lines + history_lines) + (
        f"CEO Question: {question}\n\n"
        "If the question is about the selected text, treat that selected text as the primary focus and use supporting evidence only to clarify or justify your answer. "
        "Respond as AgentCFO with structured financial guidance:"
    )
    
    return full_prompt


def _retrieve_analysis_chunks(
    db: Session,
    current_user: models.User,
    analysis_id: str,
    query_text: str,
    nova: NovaClient,
) -> List[dict]:
    """Retrieve analysis-scoped evidence chunks for a selected-text follow-up."""
    associations = (
        db.query(models.AnalysisDocument)
        .filter(models.AnalysisDocument.analysis_id == analysis_id)
        .all()
    )
    document_ids = {assoc.document_id for assoc in associations}

    if not document_ids or not query_text.strip():
        return []

    try:
        vector_store = VectorStore(nova)
        results = vector_store.search_similar(
            query=query_text,
            top_k=12,
            filter_metadata={"user_id": current_user.user_id},
        )
        filtered = [
            result for result in results
            if result.get("document_id") in document_ids
        ]
        return filtered[:4]
    except Exception as exc:
        logger.warning("Failed to retrieve supporting chunks for ask-cfo: %s", str(exc))
        return []


# =====================================================================
# Endpoint
# =====================================================================

@router.post("/ask-cfo", response_model=AskCFOResponse)
async def ask_cfo(
    request: AskCFORequest,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """
    Ask AgentCFO a financial question about a completed analysis report.
    
    AgentCFO injects the full financial context and provides CFO-level
    strategic guidance based on the report data.
    """
    
    if not request.analysis_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="analysis_id is required for Ask AgentCFO",
        )
    
    # Fetch analysis and validate ownership
    analysis = (
        db.query(models.Analysis)
        .filter(
            models.Analysis.analysis_id == request.analysis_id,
            models.Analysis.user_id == current_user.user_id,
        )
        .first()
    )
    
    if not analysis:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Analysis not found",
        )
    
    if analysis.status != "completed":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Analysis is not yet completed",
        )
    
    # Get the financial report data
    report = db.query(models.Report).filter(models.Report.analysis_id == request.analysis_id).first()
    financial_report = report.report_data if report else {}
    
    try:
        nova = NovaClient()
    except Exception as exc:
        logger.error(f"Failed to initialize Nova client for ask-cfo: {exc}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI service temporarily unavailable. Please try again.",
        )

    selected_text = request.selected_text.strip() if request.selected_text else None
    retrieval_query = "\n\n".join(part for part in [selected_text, request.question] if part)
    retrieved_chunks = _retrieve_analysis_chunks(
        db=db,
        current_user=current_user,
        analysis_id=request.analysis_id,
        query_text=retrieval_query,
        nova=nova,
    ) if selected_text else []

    # Build prompt with context injection
    prompt = _build_agentcfo_context_prompt(
        request.question,
        financial_report,
        request.chat_history,
        selected_text=selected_text,
        selected_section=request.selected_section,
        retrieved_chunks=retrieved_chunks,
    )
    
    # Call Nova Pro with AgentCFO system prompt
    try:
        logger.info(f"Invoking Nova model for ask-cfo with question: {request.question[:100]}...")
        result = nova.invoke_agent(
            prompt=prompt,
            system_prompt=AGENTCFO_SYSTEM_PROMPT,
            temperature=0.5,
            max_tokens=1500,
        )
        logger.info(f"Nova response received: {str(result)[:200]}...")
    except Exception as exc:
        logger.error(f"Nova Pro call failed in ask-cfo: {exc}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI service temporarily unavailable. Please try again.",
        )
    
    # Extract answer text
    answer = None
    if isinstance(result, dict):
        if "error" in result:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"AI model error: {result['error']}",
            )
        # NovaClient returns raw text as {"response": text, "raw_text": True}
        answer = result.get("response")
        if not answer:
            # Try other common response keys
            answer = result.get("answer") or result.get("text")
        if not answer and len(result) > 0:
            # Last resort: return first value if dict is not empty
            answer = str(list(result.values())[0])
    else:
        answer = str(result)
    
    if not answer:
        logger.error(f"No valid response text extracted from Nova result: {result}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI model returned empty response",
        )
    
    audio_base64 = None
    audio_mime_type = None

    if request.voice_response:
        try:
            voice_result = nova.synthesize_speech_with_sonic(
                text=answer,
                voice_id=request.voice_id,
                audio_format="mp3",
            )
            if isinstance(voice_result, dict) and "audio_base64" in voice_result:
                audio_base64 = voice_result.get("audio_base64")
                audio_mime_type = voice_result.get("mime_type", "audio/mpeg")
            else:
                logger.warning("Voice response requested, but Nova Sonic returned no audio")
        except Exception as voice_exc:
            logger.warning("Voice synthesis failed, returning text only: %s", str(voice_exc))

    logger.info(f"AgentCFO response generated successfully: {len(answer)} chars")
    return AskCFOResponse(
        answer=answer,
        audio_base64=audio_base64,
        audio_mime_type=audio_mime_type,
    )
